src/controllers/home.py
from flask import Blueprint, render_template, request, abort, Markup, jsonify, current_app, send_from_directory
from flask_login import current_user
from bs4 import BeautifulSoup
import os
from werkzeug.utils import secure_filename

bp = Blueprint('home', __name__)

current_directory = os.path.dirname(os.path.abspath(__file__))
template_directory = os.path.join(current_directory, 'templates')


@bp.route('/')
def homepage():
    return render_template('home.html', new_user=request.args.get("new"))


@bp.route('/save-home', methods=['POST'])
def save_home():
    if not current_user.is_authenticated or current_user.role != "admin":
        abort(401)

    try:
        home_nl_location = os.path.join(template_directory, 'home_content_nl.html')
        f = open(home_nl_location, 'w')
        soup = BeautifulSoup(request.form['homepagedataNL'], "html.parser")
        f.write(soup.prettify())
        f.close()

        home_en_location = os.path.join(template_directory, 'home_content_en.html')
        f = open(home_en_location, 'w')
        soup = BeautifulSoup(request.form['homepagedataEN'], "html.parser")
        f.write(soup.prettify())
        f.close()

        return jsonify({'success': True}), 200, {'ContentType': 'application/json'}
    except Exception as e:
        return jsonify({'success': True, 'exception': e}), 400, {'ContentType': 'application/json'}


@bp.route('/home-editor')
def home_editor():
    return render_template('home_editor.html')


@bp.route('/get-home-data')
def get_home_data():
    data_nl = render_template('home_content_nl.html')
    data_nl = Markup(data_nl.replace('\n', ''))
    data_en = render_template('home_content_en.html')
    data_en = Markup(data_en.replace('\n', ''))

    home_directory = os.path.join(current_app.config['file-storage'], 'home')
    return jsonify({"nl": data_nl, "en": data_en, "documents": os.listdir(home_directory)})


@bp.route('/get-document/<string:name>')
def get_document(name):
    if secure_filename(name):
        home_directory = os.path.join(current_app.config['file-storage'], 'home')
        return send_from_directory(home_directory, name)
    return jsonify({'success': False}), 400, {'ContentType': 'application/json'}


@bp.route('/save-document', methods=['POST'])
def save_document():
    if current_user.role != "admin":
        abort(401)

    if 'file' not in request.files:
        return jsonify({'success': False}), 400, {'ContentType': 'application/json'}

    file = request.files['file']

    if file.filename == '':
        return jsonify({'success': False}), 400, {'ContentType': 'application/json'}

    filename = secure_filename(file.filename)
    upload_dir = os.path.join(current_app.config['file-storage'], 'home')

    if not os.path.isdir(upload_dir):
        os.mkdir(upload_dir)

    # Make sure no files get overwritten
    while filename in os.listdir(upload_dir):
        filename = "1" + filename

    file.save(os.path.join(upload_dir, filename))

    return jsonify({'success': True, 'file_location': filename}), 200, {
        'ContentType': 'application/json'}


@bp.route('/remove-document/<string:name>', methods=['POST'])
def remove_document(name):
    name = secure_filename(name)
    home_directory = os.path.join(current_app.config['file-storage'], 'home')
    os.remove(os.path.join(home_directory, name))
    return jsonify({'success': True}), 200, {'ContentType': 'application/json'}

src/controllers/mails.py
from flask import Blueprint, request, jsonify, render_template
from src.utils.mail import send_contact_message, send_mail
from src.models.db import get_db
from flask_login import current_user
from src.models import EmployeeDataAccess, ProjectDataAccess, StudentDataAccess, GuideDataAccess, RegistrationDataAccess
import datetime

bp = Blueprint('mails', __name__)


@bp.route('/admin-mail')
def admin_mail():
    return render_template('mails.html')


@bp.route('/mail', methods=['POST'])
def mail():
    first_name = request.json["first-name"]
    last_name = request.json["last-name"]
    role = request.json["role"]
    message = request.json["message"]
    send_contact_message(first_name, last_name, role, message)
    return jsonify({'success': True}), 200, {'ContentType': 'application/json'}


@bp.route('/admin-mail', methods=['POST'])
def post_admin_mail():
    if not current_user.is_authenticated or current_user.role != 'admin':
        return jsonify({'success': False}), 400, {'ContentType': 'application/json'}
    data = request.get_json()
    subject = data['subject']
    content = data['content']
    receiver = data['receiver']
    lists = data['additions']

    is_student = receiver == 'students'
    if is_student:
        possible_receivers = StudentDataAccess(get_db()).get_students()
    else:
        possible_receivers = EmployeeDataAccess(get_db()).get_employees(False)

    sent = 0
    for person in possible_receivers:
        mail_content = f'Beste {person.name},\n\n{content}'
        personal_lists = mail_lists(person, is_student, lists)
        mail_content += personal_lists

        # Don't send mail if not one list is relevant for this person
        if lists and not personal_lists:
            continue

        receiver_mail = person.student_id + "@ad.ua.ac.be" if is_student else person.email
        if receiver_mail is not None:
            send_mail(receiver_mail, subject, mail_content)
            sent += 1

    return jsonify({'success': True, 'sent': sent}), 200, {'ContentType': 'application/json'}


def order_lists(lists):
    # If roll over action is present, make sure the order is correct
    # This is important for the active and archived-old lists
    if 'archived-recent' in lists:
        lists.remove('archived-recent')
        lists.append('archived-recent')
        if 'active' in lists:
            lists.remove('active')
            lists.append('active')


def mail_lists(receiver, is_student, lists: list):
    order_lists(lists)
    text = ''
    for list_type in lists:
        func = globals()[list_type.replace('-', '_')]
        text += func(receiver, is_student)
    return text


def active(receiver, is_student):
    if is_student:
        return ''
    projects = GuideDataAccess(get_db()).get_projects_for_employee(receiver.e_id)
    access = ProjectDataAccess(get_db())
    projects = [access.get_project(x['project_id'], True) for x in projects]
    if not projects:
        return ''
    text = '\n\nACTIVE'
    for project in projects:
        text += project_link(project)
    return text


def archived_recent(receiver, is_student):
    if is_student:
        return ''
    projects = GuideDataAccess(get_db()).get_projects_for_employee(receiver.e_id)
    access = ProjectDataAccess(get_db())
    projects = [access.get_project(x['project_id'], True) for x in projects]
    projects = [x for x in projects if x.is_active]
    if not projects:
        return ''
    text = '\n\nARCHIVED RECENT:'
    roll_over_performed = False
    for project in projects:
        if project_is_full(project):
            access.set_active(project.project_id, False)
            text += project_link(project)
            roll_over_performed = True
    if not roll_over_performed:
        return ''
    return text


def project_link(project):
    return f'\n<a href="https://esp.uantwerpen.be/project-page?project_id={project.project_id}">{project.title}</a>'


def project_is_full(project):
    accepted = 0
    for registration in project.registrations:
        if registration['status'] == 'Accepted':
            accepted += 1
    return accepted == project.max_students


def archived_old(receiver, is_student):
    if is_student:
        return ''
    projects = GuideDataAccess(get_db()).get_projects_for_employee(receiver.e_id)
    access = ProjectDataAccess(get_db())
    projects = [access.get_project(x['project_id'], False) for x in projects]
    projects = [project for project in projects if not project.is_active]
    if not projects:
        return ''
    text = '\n\nARCHIVED OLD:'
    for project in projects:
        text += project_link(project)
    return text


def projects_assigned_new(receiver, is_student):
    access = ProjectDataAccess(get_db())
    if is_student:
        reg_access = RegistrationDataAccess(get_db())
        all_projects = access.get_project_ids(active_only=True)
        project_ids = []
        for x in all_projects:
            registration = reg_access.get_registration(receiver.student_id, x)
            if registration:
                if registration.reg_date.year >= datetime.datetime.now().year - 1:
                    project_ids.append(registration.project)
        newly_assigned_projects = [access.get_project(x, False) for x in project_ids]
        text = "\n\nREGISTERED PROJECTS FOR THIS YEAR AND LAST YEAR:"
    else:
        projects = GuideDataAccess(get_db()).get_projects_for_employee(receiver.e_id)
        projects = [access.get_project(x['project_id'], False) for x in projects]
        text = "\n\nNEWLY ASSIGNED PROJECTS:"
        projects = filter(lambda p: p.is_active, projects)
        newly_assigned_projects = []
        for project in projects:
            newly_assigned_projects += [project for x in project.registrations if x['status'] == "Accepted"
                                        and x['last_updated'].month >= datetime.datetime.now().month - 2
                                        and x['last_updated'].year == datetime.datetime.now().year]
    if not newly_assigned_projects:
        return ''
    newly_assigned_projects = list(dict.fromkeys(newly_assigned_projects))
    for project in newly_assigned_projects:
        text += project_link(project)
    return text


def projects_pending(receiver, is_student):
    if is_student:
        return ''
    projects = GuideDataAccess(get_db()).get_projects_for_employee(receiver.e_id)
    proj_access = ProjectDataAccess(get_db())
    projects = [proj_access.get_project(x['project_id'], False) for x in projects]
    projects = filter(lambda p: p.is_active, projects)
    reg_access = RegistrationDataAccess(get_db())
    pending_projects = [x for x in projects if reg_access.get_pending_registrations(x.project_id)]
    if not pending_projects:
        return ''
    text = "\n\nPROJECTS WITH PENDING REGISTRATIONS:"
    for project in pending_projects:
        text += project_link(project)
    return text

src/controllers/supporting_lists/controller.py
from flask import Blueprint, request, render_template, jsonify
from flask_login import current_user
from src.controllers.supporting_lists.manage_lists import manage, update_item
from src.models.type import TypeDataAccess
from src.models.tag import TagDataAccess
from src.models.research_group import *
from src.models.study_field import *
from src.models.employee import *
from src.models.db import get_db

bp = Blueprint('manage_lists', __name__)


@bp.route('/modify-lists', methods=["GET", "POST"])
def modify_lists():
    """
    Handles the GET & POST request to '/modify-lists'.
    GET: requests to render page
    POST: request managing sent data
    :return: Json with failure status / template rendering / function call to manage data
    """
    if not current_user.is_authenticated or current_user.role == "student":
        return jsonify({'success': False}), 400, {'ContentType': 'application/json'}
    if request.method == "GET":
        return render_template('supporting_lists.html')
    else:
        return manage(request.json)


@bp.route('/get-all-list-data', methods=['GET'])
def get_all_list_data():
    """
    Handles the GET request to '/get-all-list-data'.
    :return: Json with all list data
    """
    conn = get_db()

    all_types = TypeDataAccess(conn).get_types(False)
    all_tags = TagDataAccess(conn).get_tags()
    all_groups = ResearchGroupDataAccess(conn).get_research_groups(False)
    all_employees = EmployeeDataAccess(conn).get_employees(False)
    all_promotors = EmployeeDataAccess(conn).get_promotors(False)

    result = {
        "types": [obj.to_dict() for obj in all_types],
        "tags": all_tags,
        "research groups": [obj.to_dict() for obj in all_groups],
        "employees": [obj.to_dict() for obj in all_employees],
        "promotors": [obj.to_dict() for obj in all_promotors]
    }

    return jsonify(result)


@bp.route("/update-profile", methods=["POST"])
def update_profile():
    """
    Handles the POST request to '/update-profile'.
    :return: function call to update_item with sent data
    """
    return update_item(request.json)

src/templates/contact.html
{% extends "layout.html" %}

{% block title %}Contact{% endblock %}
{% block nav_contact %}active{% endblock %}

{% block head %}

    <script src="{{ url_for('static', filename='js/contact.js') }}"></script>

{% endblock %}

{% block content %}


<div class="container">

    <h5 style="margin-bottom: 20px">{{ get_text("Contact Message") }}</h5>

    <div class="input-group">
        <input class="form-control" type="text" id="first-name" name="first-name" placeholder="{{ get_text("First Name") }}"/>
        <input class="form-control" type="text" id="last-name" name="last-name" placeholder="{{ get_text("Last Name") }}"/>
        <select class="custom-select" id="role" name="role">
            <option value="student">Student</option>
            <option value="employee">{{ get_text("Employee") }}</option>
        </select>
    </div>

    <textarea id="message" class="form-control" rows="3" placeholder="{{ get_text("Your message") }}"
              style="margin-top: 10px"></textarea>

    <br/>

    <button id="send-button" class="btn btn-primary" style="margin-right: 10px">{{ get_text("Send") }}</button>
    <span id="status"></span>

</div>


{% endblock %}

src/templates/footer.html
<footer class="site-footer box-shadow" style="background-color: rgba(0,0,0,0.03)" >

    <!-- Contact -->
    {% if current_language == "nl" %}

    <div class="footer-copyright text-center py-3" style="margin-top: 10px">Vragen?
        Contacteer ons <a href="mailto://{{ contact_mail }}">via mail</a> of <a href="{{ url_for('contact') }}">via formulier</a>!
    </div>

    {% else %}

    <div class="footer-copyright text-center py-3" style="margin-top: 10px">Questions?
        Contact us <a href="mailto://{{ contact_mail }}">by mail</a> or <a href="{{ url_for('contact') }}">by form</a>!
    </div>

    {% endif %}

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3" style="padding-bottom: 0px; margin-bottom: 0px">
        © Universiteit Antwerpen
    </div>

</footer>

src/templates/home.html
{% extends "layout.html" %}

{% set nav_home = "active" %}

{% block title %}Home{% endblock %}

{% block content %}

    <div class="container">

        {% if new_user %}
            <div class="alert alert-success text-center">Welcome to the ESP site! Please complete your profile in the settings tab</div>
        {% endif %}

        {% if current_language == "nl" %}

        {% include 'home_content_nl.html' %}

        {% else %}

        {% include 'home_content_en.html' %}

        {% endif %}

    </div>

{% endblock %}

src/templates/home_content_nl.html
<div class="text-center">
 <h1 class="display-4">
  ESP UAntwerpen
 </h1>
 <p style="font-size: 1.25em;">
     Als student Informatica kan je deze website gebruiken om te zoeken naar een geschikte <strong>thesis</strong> of <strong>stage</strong>.
     <strong>Deadlines</strong> voor registratie en indiening zijn te vinden op de geschikte Blackboard pagina's.
  Alle beschikbare thesissen en stages staan op de Projecten pagina.
  <br>
  Richtlijnen in de
  <strong>
    onderstaande officiële documenten.
  </strong>
 </p>

<h4>Registratie Info</h4>
<p style="font-size: 1.25rem">
Vanaf academiejaar 2019-2020 worden alle thesissen en stages
administratief opgevolgd via een online registratieprocedure.
    Je start de <strong>registratie</strong> op via
<u><a href="https://studhelp.uantwerpen.be/inschrijvingen/knowledgebase.php?article=374">
SisA (Aanvragen-Mobiliteit-Aanvraag van Mobiliteit/Stage)</a></u>
en vervolledigt het proces via Mobility Online.
    <br>

In Mobility Online is dit proces opgebouwd als een flow, die je stap per stap gidst door de stageadministratie.

Je ontvangt alle nodige documenten via het stappenplan.
    Zorg ervoor dat je het administratieve proces voltooid hebt uiterlijk <strong>3 weken vóór</strong> de start van de stage.

Pas na voltooiing van alle stappen krijg je de finale goedkeuring om te starten.
<strong>
Enkel bij finale goedkeuring ben je verzekerd als stagiair.
</strong>
 </p>
    <br>
</div>



<div class="d-flex justify-content-center align-items-center">
 <div class="card text-center" style="width: 22rem">
  <div class="card-header">
   <h4 class="my-0">
    Master thesis
   </h4>
  </div>
  <div class="card-body">
   <ul class="list-unstyled">
    <li>
     <a href="get-document/RichtlijnenMasterproefInformaticaJuni2021FINAL.pdf" target="_blank">
      Richtlijnen
     </a>
    </li>
    <li>
    </li>
    <li>
     <a data-toggle="collapse" href="#master-forms">
      Beoordelingsformulieren
     </a>
     <div class="collapse" id="master-forms">
      <ul class="list-unstyled">
       <li>
        <hr/>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-FormeelModel.docx">
         Formeel model
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-Gevalsanalyse.docx">
         Gevalsanalyse
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-Haalbaarheidsstudie.docx">
         Haalbaarheidsstudie
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-Literatuurstudie.docx">
         Literatuurstudie
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-ProcesEvaluatie.docx">
         Proces evaluatie
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-Simulatie.docx">
         Simulatie
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-VergelijkendeStudie.docx">
         Vergelijkende studie
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-AdHoc.docx">
         AdHoc
        </a>
       </li>
      </ul>
     </div>
    </li>
    <li>
     <hr/>
     <a href="get-document/GuidelinesMasterThesisComputerScienceJune2021FINAL.pdf" target="_blank">
      Guidelines
     </a>
    </li>
    <li>
     <a data-toggle="collapse" href="#master-forms-en">
      Assessment Forms
     </a>
     <div class="collapse" id="master-forms-en">
      <ul class="list-unstyled">
       <li>
        <hr/>
       </li>
       <li>
        <a href="get-document/AssessmentForm-FormalModel.docx">
         Formal model
        </a>
       </li>
       <li>
        <a href="get-document/AssessmentForm-CaseStudy.docx">
         Case study
        </a>
       </li>
       <li>
        <a href="get-document/AssessmentForm-FeasibilityStudy.docx">
         Feasibility study
        </a>
       </li>
       <li>
        <a href="get-document/AssessmentForm-LiteratureStudy.docx">
         Literature study
        </a>
       </li>
       <li>
        <a href="get-document/AssessmentForm-ProcessEvaluation.docx">
         Process evaluation
        </a>
       </li>
       <li>
        <a href="get-document/AssessmentForm-Simulation.docx">
         Simulation
        </a>
       </li>
       <li>
        <a href="get-document/AssessmentForm-ComparativeStudy.docx">
         Comparative study
        </a>
       </li>
       <li>
        <a href="get-document/Beoordelingsformulier-AdHoc.docx">
         AdHoc
        </a>
       </li>
      </ul>
     </div>
    </li>
   </ul>
  </div>
 </div>
</div>

src/templates/home_editor.html
{% extends "layout.html" %}

{% block title %}Home Editor{% endblock %}

{% block head %}

<script src="{{ url_for('static', filename='js/lib/ckeditor/ckeditor.js') }}"></script>
<script src="{{ url_for('static', filename='js/lib/dropzone.js') }}"></script>
<script src="{{ url_for('static', filename='js/home.js') }}"></script>
<script src="{{ url_for('static', filename='js/lib/bootstrap4-toggle.min.js') }}"></script>


<link rel="stylesheet" href="{{ url_for('static', filename='css/lib/dropzone.css') }}" type="text/css">
<link rel="stylesheet" href="{{ url_for('static', filename='css/lib/bootstrap4-toggle.min.css') }}" type="text/css">

{% endblock %}

{% block content %}

<div class="container">

<h3 id="description-title" class="my-2">Your description in <input id="description-toggle"
                                                                 type="checkbox" checked
                                                                 data-toggle="toggle"
                                                                 data-onstyle="info" data-on="EN"
                                                                 data-off="NL"></h3>

    <div id="editor">
    </div>

    <div class="card my-4" id="documents">
        <div class="card-body">
            <h4>Documents</h4>
            <ul class="list-unstyled d-inline" id="documents-list">
            </ul>
        </div>
    </div>

    <form action="{{ url_for('home.save_document') }}"
                  class="dropzone my-4"
                  id="dropzone"></form>





    <button name="submitbtn" id="submitbtn" class="btn btn-secondary float-right">Save homepage</button>

</div>




{% endblock %}

src/templates/nav.html
{% if current_theme == "dark" %}

    {% set navbar_classes="navbar-dark bg-dark" %}
    {% set login_classes="btn-light" %}
    {% set logout_classes="btn-outline-light" %}
    {% set settings_classes="btn-dark" %}
    {% set secondary_color="bg-info text-white" %}

{% else %}

    {% set navbar_classes="navbar-light bg-light border-bottom" %}
    {% set login_classes="btn-dark" %}
    {% set logout_classes="btn-outline-dark" %}
    {% set settings_classes="btn-light" %}
    {% set secondary_color="" %}

{% endif %}

<!-- Project extension modal -->
<div id="extension-modal"></div>

<nav class="navbar navbar-expand-sm fixed-top box-shadow {{ navbar_classes }}">

    <div class="container">

        <!-- UA Image -->
        <a class="navbar-brand" href="{{ url_for('home.homepage') }}">

            {% if current_theme == "light" %}
                <img src="{{ url_for('static', filename='images/logo-en.svg') }}" height="40" alt="">
            {% else %}
                <img src="{{ url_for('static', filename='images/white-logo.png') }}" height="30" alt="">
            {% endif %}

        </a>

        <!-- Toggle for small screens -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <!-- All other content -->
        <div class="collapse navbar-collapse" id="navbarText">

            <ul class="navbar-nav mr-auto ml-auto">
                <li class="nav-item {{ nav_home }}">
                    <a class="nav-link" href="{{ url_for('home.homepage') }}">{{ get_text("Home") }}</a>
                </li>
                <li class="nav-item {{ nav_projects }}">
                    <a class="nav-link" href="{{ url_for("projects.projects") }}">{{ get_text("All Projects") }}</a>
                </li>

                {% if current_user.is_authenticated and current_user.role != "student" %}
                    <li class="nav-item {{ nav_myprojects }}">
                        <a class="nav-link" href="{{ url_for("projects.my_projects", employee=current_user.name, edit="true") }}">{{ get_text("My Projects") }}</a>
                    </li>
                {% endif %}

            </ul>

            {% if current_user.is_authenticated and current_user.role != "student" %}

                <div class="dropdown">

                    <!-- Bell Icon -->
                    <button style="margin-right: 10px;" id="options" class="btn" type="button" data-toggle="dropdown"
                            aria-haspopup="true" aria-expanded="false">
                        {% if current_theme == "light" %}
                            <span style="font-size:20px; color: rgba(0,0,0,.5);">&#128365;</span>
                        {% else %}
                            <span style="font-size: 20px; color:white">&#128365;</span>
                        {% endif %}
                        <span class="badge danger-color" id="notification-count"></span>
                    </button>

                    <!-- Dropdown Items -->
                    <ul class="dropdown-menu" role="menu" id="notifications">
                        <script>notifications("{{ current_user.name }}", '{{ get_text("New registration") }}', '{{ get_text("New extension") }}', '{{ current_language }}')</script>
                    </ul>

                </div>

            {% endif %}


            <div class="dropdown">

                <!-- Gear Icon -->
                <button style="margin-right: 10px" id="options" class="btn {{ settings_classes }}" type="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span style="font-size: 20px;  color: rgba(0,0,0,.4)">&#9881;</span>
                </button>

                <!-- Dropdown items -->
                <div class="dropdown-menu dropdown-menu-left" aria-labelledby="options">
                    {% if current_language == "en" %}
                        <a class="dropdown-item" href="{{ request.script_root + get_args() + "&lang=nl" }}">Nederlands</a>
                    {% else %}
                        <a class="dropdown-item" href="{{ request.script_root + get_args() + "&lang=en" }}">English</a>
                    {% endif %}

                    {% if current_theme == "light" %}
                        <a class="dropdown-item"
                           href="{{ request.script_root + get_args() + "&theme=dark" }}">{{ get_text("Dark Theme") }}</a>
                    {% else %}
                        <a class="dropdown-item"
                           href="{{ request.script_root + get_args() + "&theme=light" }}">{{ get_text("Light Theme") }}</a>
                    {% endif %}

                    {% if current_user.is_authenticated and (current_user.role == "employee" or current_user.role == "admin") %}
                        {% if not archive_active %}
                            <a class="dropdown-item"
                               href="{{ request.script_root + get_args() + "&archive=true" }}">{{ get_text("Show Inactive") }}</a>
                        {% else %}
                            <a class="dropdown-item"
                               href="{{ request.script_root + get_args() + "&archive=false" }}">{{ get_text("Hide Inactive") }}</a>
                        {% endif %}
                    {% endif %}

                    {% if current_user.is_authenticated and (current_user.role == "admin" or current_user.role == "employee") %}
                        <hr>
                        <span class="dropdown-item" style="color: grey; font-size: 14px">{{ get_text("Manage") }}</span>
                        <a class="dropdown-item" href="#" id="my-profile">{{ get_text("My Profile") }}</a>

                        {% if current_user.role == "admin" %}
                            <a class="dropdown-item" href="{{ url_for("projects.get_overview") }}">{{ get_text("Overview") }}</a>
                            <a class="dropdown-item" href="#" id="my-csv">{{ get_text("project-csv") }}</a>
                            <a class="dropdown-item"
                               href="{{ url_for("manage_lists.modify_lists") }}">{{ get_text("Supporting Lists") }}</a>
                            <a class="dropdown-item" href="{{ url_for("mails.admin_mail") }}" id="extension-confirmation">Admin Mails</a>
                        {% endif %}
                    {% endif %}

                </div>

            </div>

            <!-- Login button -->
            {% if current_user.is_authenticated %}
                <form action="{{ url_for('auth.logout') }}">
                    <button type="submit" class="btn my-2 my-sm-0 {{ logout_classes }}"
                            id="logout">{{ get_text("Logout") }}</button>
                </form>
            {% else %}
                <form action="{{ url_for('auth.login') }}">
                    <script> document.cookie = "sessionAction=;expires=Thu, 01 Jan 1970 00:00:01 GMT"</script>
                    <!-- makes sure session is inactive when logged out -->
                    <button type="submit" class="btn my-2 my-sm-0 {{ login_classes }}"
                            id="login">{{ get_text("Login") }}</button>
                </form>
            {% endif %}
        </div>

        <!-- Registration Modal -->
        <div class="modal fade" id="registrations_modal" tabindex="-1" role="dialog" aria-hidden="true"
             style="display: none;">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">{{ get_text("Registrations") }}</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>

    </div>
</nav>